type: job
name: sfm-trt-convert-large
image:
  type: build
  build_source:
    type: git
    repo_url: https://github.com/reyashv/slb-pov
    ref: be9d7dc8920cfb19d5b70216d07db31da6041239
    branch_name: restructure/slb-pov
  build_spec:
    type: dockerfile
    build_context_path: ./encoders/sfm/
    dockerfile_path: ./encoders/sfm/Dockerfile.trt
    command: python convert_trt.py
trigger:
  type: manual
resources:
  node:
    type: node_selector
    capacity_type: on_demand
  devices:
    - name: L40S
      type: nvidia_gpu
      count: 1
  cpu_request: 4
  cpu_limit: 8
  memory_request: 27200
  memory_limit: 48000
  ephemeral_storage_request: 50000
  ephemeral_storage_limit: 100000
env:
  MODEL_DIR: ${ARTIFACT_SFM_LARGE}
  SFM_ARCH: vit_large_patch16
  SFM_IMG_SIZE: '224'
  OUTPUT_ARTIFACT_NAME: sfm-large-trt-engine
workspace_fqn: ${WORKSPACE_FQN}
retries: 1
timeout: 7200
